spring:
  application:
    name: report-etl
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect:
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: job